synonyms = {
    'altmer': 'altmer',
    'alt': 'altmer',
    'high elf': 'altmer',
    'he': 'altmer',
    'argonian': 'argonian',
    'arg': 'argonian',
    'lizard': 'argonian', #LGM = little green men / lusty green maiden
    'bosmer' : 'bosmer',
    'bos' : 'bosmer',
    'wood elf': 'bosmer',
    'we': 'bosmer',
    'breton': 'breton',
    'bre': 'breton',
    'dunmer': 'dunmer',
    'dark elf': 'dunmer',
    'dun': 'dunmer',
    'de': 'dunmer',
    'imperial': 'imperial',
    'imp': 'imperial',
    'cyr': 'imperial',
    'khajiit': 'khajiit',
    'kha': 'khajiit',
    'cat': 'khajiit',
    'nord': 'nord',
    'nor': 'nord',
    'orc': 'orc',
    'ors': 'orc',
    'orsimer': 'orc',
    'redguard': 'redguard',
    'red': 'redguard',
    'rdg': 'redguard',
    'male': 'm',
    'm': 'm',
    'man': 'm',
    'mail': 'm', # lol
    'female': 'f',
    'f': 'f',
    'woman': 'f',
    'surname': 's',
    's': 's',
    'sur': 's',
    'last name': 's',
    'garbage in' : 'garbage out'
}

names = {
    'bosmer': {
        'f': [
            "Aerin", "Aglaril", "Anrel", "Aradraen", "Arangaer", "Aranwen",
            "Ardhil", "Aredhel", "Bauril", "Baurin", "Belwen", "Berwen",
            "Borwen", "Celegil", "Cirwedh", "Cuunel", "Distel", "Dondreth",
            "Dothiel", "Dothruviel", "Eindel", "Elegnan", "Elphiron", "Emelin",
            "Eraldil", "Estinan", "Falion", "Fara", "Filbeneth", "Galbedir",
            "Galdiir", "Gelduin", "Gildan", "Giningil", "Glathel", "Hyna",
            "Iingail", "Indrel", "Irwaen", "Kirsty", "Liette", "Lorchel",
            "Mara", "Menelin", "Milbereth", "Nael", "Natesse", "Nathien",
            "Nilioniel", "Nona", "Penglithil", "Radras", "Samia", "Thaeril",
            "Adanrel", "Angrond", "Alawen", "Althel", "Andragil", "Anedhel",
            "Boroneth", "Bothiel", "Carwen", "Ciindil", "Dagail", "Dairihill",
            "Degil", "Dennilwen", "Dredhwen", "Elragail", "Elsynia",
            "Faurinthil", "Ganredhel", "Githriian", "Hasathil", "Huurwen",
            "Idrolian", "Laenafil", "Laralthir", "Mandil", "Methredhel",
            "Naarifin", "Nilawen", "Parwen", "Syl", "Telaendril", "Thaedil",
            "Thalfin", "Thamriel", "Thiirchel", "Uurwen", "Anuriel", "Ardwen",
            "Beleval", "Brelas", "Galathil", "Nimphaneth", "Nimriel", "Nivenor",
            "Wylandriah", "Adagwen", "Aeranir", "Aerchith", "Aerwaen", "Agafos",
            "Agilruin", "Alandis", "Alangil", "Alareth", "Aldeth", "Aleanneth",
            "Althoth", "Althuviel", "Amariel", "Andoriel", "Andrathel",
            "Anenya", "Anerel", "Anganrith", "Angeniel", "Anglith", "Angranel",
            "Angrel", "Angren", "Angrineth", "Aniel", "Annarth", "Annathiel",
            "Anriel", "Aradhel", "Araneth", "Arathel", "Arithiel", "Athemel",
            "Atheval", "Athirion", "Balia", "Belane", "Berisse", "Betedir",
            "Birwaen", "Bondileth", "Boriel", "Borogilmith", "Borwaeneth",
            "Bothiel", "Bowenas", "Bredrel", "Brelinith", "Brendil", "Calendir",
            "Calenethel", "Calithil", "Canda", "Candariel", "Candion",
            "Caraleth", "Caralith", "Caranith", "Cariel", "Cayliss",
            "Celaranith", "Celorien", "Celwen", "Cenrathil", "Cerwaenor",
            "Cerweriell", "Cerwil", "Ciinderel", "Ciindewal", "Ciireriath",
            "Cirithiel", "Coradri", "Cwynoniel", "Cygwen", "Cygwenn",
            "Dailalleth", "Dailinthil", "Dailirwen", "Dailithil", "Dairaegal",
            "Dalaneth", "Darahawn", "Daraneth", "Dayagwen", "Degail",
            "Denninel", "Dinwenel", "Dirwendel", "Doldoniel", "Dolian",
            "Dolirdor", "Dollian", "Dondrothel", "Doneth", "Donganiel",
            "Dongenan", "Donglanel", "Donnaelain", "Donnenir", "Donniel",
            "Donriel", "Doralin", "Doralineth", "Dorathil", "Doriel",
            "Dothriel", "Drauginas", "Earnaana", "Edherien", "Efreghar",
            "Egilrineth", "Einnel", "Einrel", "Einriel", "Elanas", "Elandora",
            "Elayel", "Elengil", "Elerdel", "Elethien", "Elirwen", "Elphaniel",
            "Elphinia", "Elphiniel", "Elphirion", "Elriniel", "Elruin",
            "Elsaril", "Elsenia", "Elsonia", "Emalith", "Emanir", "Emolwen",
            "Emoneth", "Emuin", "Endoriell", "Endregail", "Endrith", "Enduinas",
            "Eneriell", "Engail", "Englornith", "Enielin", "Eniras", "Enlorien",
            "Enruvie", "Eralian", "Eralin", "Eraneth", "Eranwen", "Erathrin",
            "Erelruin", "Erilthil", "Erinel", "Ernethel", "Ernethiel", "Erwin",
            "Essaneth", "Essilion", "Essonarth", "Estelin", "Estilion",
            "Ethrel", "Eveli", "Faedre", "Faenir", "Faldethil", "Falphirion",
            "Fanadis", "Fanayell", "Fandir", "Fangil", "Faraniel", "Farenlith",
            "Fariel", "Faruin", "Farwen", "Fauridil", "Fauril", "Faurwin",
            "Fayadess", "Fayagwen", "Fayilien", "Felariel", "Fiabess",
            "Filberel", "Filedh", "Filenarth", "Filoneth", "Finde", "Findredil",
            "Fingil", "Fingrathel", "Finnethil", "Finnorieth", "Finoriell",
            "Firalboreth", "Firanarth", "Firathil", "Firchel", "Firiliril",
            "Firion", "Fironel", "Firuin", "Firwin", "Fisalie", "Flanneth",
            "Floriele", "Frenidela", "Frenith", "Gaette", "Gaireth",
            "Galathril", "Galbenel", "Galdini", "Galereth", "Galerond",
            "Galesse", "Galthel", "Gananith", "Gannel", "Ganniel", "Ganrenan",
            "Ganwen", "Garaengrin", "Garamiel", "Garanel", "Gariel", "Garimmir",
            "Garion", "Garniel", "Garwiril", "Garwiruin", "Gathiel", "Gathion",
            "Gathraenor", "Gathwen", "Geldirel", "Gelthedh", "Gelthiras",
            "Gelur", "Genboril", "Gendinora", "Genriel", "Genthel", "Geoffrise",
            "Gerethel", "Gerinien", "Gerwen", "Gerweruin", "Gethawen",
            "Gilbonel", "Gilinora", "Gilradil", "Gilraen", "Gilriian",
            "Gindothel", "Ginereth", "Giniel", "Girnalin", "Girnileth",
            "Girriian", "Githiril", "Githriian", "Glaras", "Glardel", "Glarin",
            "Glendora", "Glooredel", "Gloraneth", "Glordil", "Glothorien",
            "Gluineth", "Gosellaneth", "Grildoriel", "Guilenarth", "Guileval",
            "Guilion", "Gwaerarth", "Gwaering", "Gwendis", "Gwenieth",
            "Halsinan", "Hangaerin", "Hanriian", "Harmolith", "Hasiwen",
            "Henoreth", "Henriel", "Henrinora", "Heragaeth", "Herdor",
            "Honorata", "Huunel", "Huurel", "Iannianith", "Ianwaen", "Idronel",
            "Idrothiel", "Iirdel", "Iirdilin", "Iirond", "Iirwaen", "Imriel",
            "Indanas", "Indithil", "Indrenan", "Indraseth", "Ingarthel",
            "Inril", "Irdan", "Irwiraen", "Kaale", "Kashia", "Kathariel",
            "Kirstenreth", "Kuna", "Laen", "Laeneval", "Laerinir", "Laerion",
            "Laniriel", "Lanwaen", "Lara", "Laranieth", "Larasel", "Larchelas",
            "Larweneth", "Lathriel", "Lianorien", "Lienanarth", "Lienenarth",
            "Liennas", "Lilaneth", "Lionora", "Lirond", "Little Leaf",
            "Lobelathel", "Lorading", "Lorregil", "Lorwen", "Lothiel", "Maelin",
            "Malaniel", "Malareth", "Malesse", "Malfinir", "Malioneth",
            "Mariel", "Marineth", "Marinora", "Megail", "Mehlin", "Melbethil",
            "Melledh", "Melothil", "Melrethel", "Menaelion", "Mendil",
            "Mendredhil", "Mengaer", "Meninel", "Mennel", "Menninia", "Mennir",
            "Menwirchel", "Miliril", "Millenith", "Minaelion", "Mindirin",
            "Miniel", "Minonel", "Minriel", "Minrion", "Mithen", "Molamiel",
            "Molenaniel", "Moleras", "Moneriel", "Naarendras", "Naeldil",
            "Naerion", "Naeronel", "Naerorien", "Nallion", "Namriel", "Nara",
            "Naridir", "Narinarth", "Narion", "Nelmir", "Nielaenor", "Nielas",
            "Nien", "Nienras", "Nieth", "Nilara", "Nilbedel", "Nilbethil",
            "Nilenarth", "Nilleth", "Nilliel", "Nilwen", "Nimanir", "Nimriell",
            "Nimriian", "Nindenel", "Ninriledh", "Ninwin", "Niranda",
            "Niraniel", "Niriel", "Niruin", "Nistel", "Nistyniel", "Nithelin",
            "Nithiel", "Nitholeth", "Nithriel", "Nivrel", "Nivriian",
            "Nivrilin", "Noldathil", "Norraneth", "Norriel", "Norweras",
            "Nothemril", "Onglorien", "Orabess", "Oraneth", "Orchelith",
            "Oriadess", "Orianel", "Orwinora", "Panreth", "Parenel", "Pariel",
            "Parwaen", "Parwinel", "Peruin", "Pishna", "Ralaenglin", "Ralai",
            "Ralayell", "Ralerdhil", "Ralion", "Ranais", "Rangil", "Ranneth",
            "Ranniel", "Rathril", "Rayniir", "Raynorien", "Rendorien",
            "Rialanith", "Riian", "Rilineth", "Rinareth", "Rindirre", "Rithros",
            "Rodaeril", "Rothariel", "Sanithil", "Sariel", "Saronithel",
            "Selene", "Sellineth", "Sendel", "Sendranir", "Serchel", "Serwin",
            "Sethel", "Sirreth", "Syalleth", "Teliwen", "Tellanil",
            "Thaedothiel", "Thael", "Thaeliwaen", "Thaellin", "Thaelril",
            "Thaeniril", "Thaenor", "Thaeraen", "Thaereledh", "Thaerin",
            "Thaesse", "Thalorel", "Thalrinel", "Thamenarth", "Thamraen",
            "Thamrin", "Thariel", "Tharuin", "Thiirion", "Thiirril", "Thralin",
            "Ulladhel", "Uunniel", "Uunril", "Uurdhel", "Uurwaerion", "Vendyne",
            "Viriniel", "Wendirre", "Whisper", "Zahimah", "Zifri", "Baham",
            "Benieth", "Dagla", "Fara", "Iinel", "Laenril", "Radreth"
        ],
    
        'm': [
            "Aengoth", "Agarond", "Allimir", "Alveleg", "Amring", "Anglalos",
            "Anruin", "Arannir", "Arathor", "Baradras", "Berengeval", "Bolrin",
            "Bragor", "Brallion", "Brithroth", "Brolmir", "Celegorn", "Cingor",
            "Clendil", "Cun", "Dangor", "Denegor", "Dirding", "Dondir",
            "Elberoth", "Elegal", "Eloroth", "Endring", "Engaer", "Eradan",
            "Erradan", "Erval", "Faldan", "Fargoth", "Faulgor", "Fillin",
            "Findulain", "Foronir", "Gaeldol", "Gaenor", "Galmir",
            "Galthragoth", "Gazalem", "Gerrilgor","Glaum", "Glonagoth",
            "Godros", "Gorchalas", "Hingor", "Meldor", "Menelras", "Minedhel",
            "Minglos", "Monthadan", "Morth", "Nalion", "Nedhelas", "Nedhelorn",
            "Pegasai", "Peragon", "Rithrannir", "Tarhiel", "Thoromlallor",
            "Thoronor", "Tuundir", "Ulwaen", "Ungeleb","Aengvir", "Amragor",
            "Anglor", "Anguilon", "Athragar", "Athrelor", "Baenlin",
            "Baeralorn", "Brellin", "Brithaur", "Brodras", "Bolwing", "Caenlin",
            "Caenlorn", "Cingaer", "Cingor", "Daenlin", "Dervenin", "Engorm",
            "Enilroth", "Eridor", "Erthor", "Fimmion", "Fithragaer", "Foroch",
            "Gelephor", "Glarthir", "Gloorolros", "Gundalas", "Gwinas",
            "Hagaer", "Hundolin", "Maenlorn", "Maglir", "Nedhelfin", 
            "Niraegaer", "Nordinor", "Rindir", "Thadon", "Thaurron", "Thoronir",
            "Thrangirfin", "Thurindil", "Ungolim", "Urunil", "Uungor", "Uuras",
            "Anoriath", "Dervenin", "Edorfin", "Elrindir", "Endrast", "Enthir",
            "Faendal", "Gadnor", "Gelebros", "Girduin", "Gwilin", "Malborn",
            "Niruin", "Orchendor", "Ronthil", "Syndus", "Thaer", "Ungrien",
            "Valindor"
        ],
    
            
        's': [
            "Arrow-Catcher", "Beesinger", "Birdsong", "Blood-Letter",
            "Branchbreaker", "Callushands", "Daintyfoot", "Drurel",
            "Ever-Festering", "Flameheart", "Food-Finder", "Forestsmasher",
            "Garnona", "Grubnose", "Light-Tongued", "Longshot", "Many-Legs",
            "Ramothran", "Sells-All", "Sharp-Arrow", "Skeever-Face",
            "Stickyfoot", "the Banekin Handler", "the Bold", "the Brewmaster",
            "the Dark", "the Daunted", "the Doorwalker", "the Dreg",
            "the Farflung", "the Headscratcher", "the Hearteater", "the Hound",
            "the Impaler", "the Ironbark", "the Ironhand", "the Kill-Happy",
            "the Light", "the Outcast", "the Pale", "the Redbeard",
            "the Shadow", "the Sly", "Thistlebreeches", "Tree-Killer",
            "Two-Tongue", "Vayn", "Woodwalker"
        ]
    }
}